services:
  db:
    image: mariadb
    ports:
      - '3306:${MARIADB_PORT:-3306}'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-tickets_db}
      MARIADB_USER: ${MARIADB_USER:-root}
